<a href="https://colab.research.google.com/github/FGalvao77/others-knowledge-in-python-for-data-science/blob/main/Introdu%C3%A7%C3%A3o_ao_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TensorFlow**

TensorFlow é uma biblioteca de código aberto para aprendizado de máquina aplicável a uma ampla variedade de tarefas. É um sistema para criação e treinamento de redes neurais para detectar e decifrar padrões e correlações, análogo (mas não igual) à forma como humanos aprendem e raciocinam.[3] Ele é usado tanto para a pesquisa quanto produção no Google, e está aos poucos substituindo seu antecessor de código proprietário, DistBelief.

TensorFlow foi desenvolvido pela equipe Google Brain para uso interno na empresa. Foi lançado sob a licença de código aberto Apache 2.0 em 9 de novembro de 2015.

### **História**

**DistBelief** 

A partir de 2011, a Google Brain construiu DistBelief como um sistema proprietário para aprendizagem de máquina baseado em aprendizagem profunda em redes neurais. Seu uso cresceu rapidamente pelas diversas empresas do grupo Alphabet em pesquisa e aplicações comerciais.O Google colocou vários programadores, incluindo Jeff Dean, para simplificar e refatorar o código base de DistBelief para que fosse mais rápido, mais robusto e uma biblioteca que poderia ser usada por aplicativos, e esse projeto eventualmente tornou-se o TensorFlow. Em 2009, a equipe, liderada por Geoffrey Hinton, tinha implementado backpropagation generalizada e outras melhorias, o que permitiu a geração de redes neurais com muito maior precisão, como uma redução de 25% de erros no reconhecimento de fala.

**TensorFlow**

TensorFlow é a segunda geração do sistema projetado pelo Google Brain. A versão 1.0.0 foi lançada em 15 de fevereiro de 2015. Embora a implementação de referência seja executada em dispositivos individuais, TensorFlow pode também ser executado em múltiplas CPUs e GPUs (com extensões opcionais CUDA para GPGPU). TensorFlow está disponível em versões de 64 bits Linux, MacOS, Windows e plataformas de computação móveis, incluindo Android e iOS.

Cálculos no TensorFlow são expressos como grafos de fluxo de dados mantendo um estado. O nome TensorFlow deriva das operações que tais redes neurais realizam em arranjos de dados multidimensionais. Estas matrizes são chamadas de "tensores". Em junho de 2016, Dean afirmou que 1.500 repositórios no GitHub mencionavam TensorFlow, dos quais apenas 5 eram do Google.

**Tensor Processing Unit (TPU)**

Em maio de 2016, o Google anunciou o seu tensor processing unit (TPU), um ASIC construído especificamente para aprendizado de máquina e adaptado para o TensorFlow. TPU é um acelerador de inteligência artificial programável projetado para fornecer alta taxa de transferência para aritmética de baixa precisão (como 8 bits), e orientada para o uso ou a execução de modelos, ao invés de treino. O Google anunciou que estava usando TPUs dentro de seus centros de dados há mais de um ano, e constatou que eles conseguiam uma otimização uma ordem de magnitude melhor em performance por watt para aprendizado de máquina.

Em maio de 2017, o Google anunciou a segunda geração, bem como a disponibilidade dos TPUs no Google Compute Engine.A segunda geração de TPUs alcança até 180 teraflops de desempenho, e quando organizados em clusters de 64 TPUs, fornecem até 11.5 petaflops.

**TensorFlow Lite**

Em maio de 2017, o Google anunciou um stack de software especificamente para desenvolvimento Android, TensorFlow Lite,[14] começando com Android Oreo.

**Aplicações**
O Google lançou oficialmente RankBrain em 26 de outubro de 2015, apoiado pelo TensorFlow.

### **Recursos**
TensorFlow fornece uma API em Python, bem como C++, Haskell, Java, Go, e Rust. Pacotes de terceiros estão disponíveis para C#, Julia, R e Scala.

Entre as aplicações para as quais TensorFlow é a base, estão software de classificação automatizada de imagens, como o DeepDream.RankBrain agora lida com um número substancial de consultas de pesquisa, substituindo e complementando o algoritmo estático tradicional de busca baseado em resultados.

fonte:
 - https://pt.wikipedia.org/wiki/TensorFlow


**Para se aprofundar acesse o site oficial:**
 - https://www.tensorflow.org/

**Canal oficial no YouTube:**
 - https://www.youtube.com/channel/UC0rqucBdTuFTjJiefW5t-IQ

In [ ]:
# importando as bibliotecas
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [ ]:
# importando o dataset
# este dataset já está embutido na biblioteca "keras"
fashion_mnist = keras.datasets.fashion_mnist

In [ ]:
# separando os dados de treino e teste
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [ ]:
# verificando o tamanho da base de treino - tensor 3D
train_images.shape # 60000 elementos de matrizes de 28 por 28

(60000, 28, 28)

In [ ]:
# verificando o tamanho dos rótulos de treino
len(train_labels)

60000

In [ ]:
# verificando os rótulos da base de treino
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [ ]:
# conferindo o tamanho da base de teste - tensor 3D
test_images.shape # 10000 elementos de matrizes de 28 por 28

(10000, 28, 28)

In [ ]:
# verificando a quantidade de rótulos na base de teste
len(test_images)

10000

In [ ]:
# verificando os rótulos de teste
# por questão de limitação de espaço (total de 10.000)
# é somente exibido os três primeiros e três últimos rótulos de teste
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [ ]:
# as imagens de treino e teste é  composta ppr matriz de 28 por 28
# e cada um desses elementos da matriz é exatamente um pixel entre 0 e 255
# sendo 0 ausência de cor e 255 máxima intensidade de cor
# e alguns modelos, tais como a regressão linear e as próprias redes neurais, eles se beneficiam de atributos escalados
# eles utilizam uma técnica de gradiente para otimização - uma derivada

# transformando nossa imagem em escala pequena
# como nossa imagem tem entre 0 e 255 pixels
# então podemos dividir a matriz 
# portanto o pixel com maior intensidade de 255 será igual 1
# de menor intensidade que é 0 continuará sendo 0
# e os de intensidade intermediária estará entre 0 e 1
# dessa forma, implicitamente estamos utilizando o "MinMaxScaller" sem chamá-lo

train_images = train_images / 255.0

test_images = test_images / 255.0

In [ ]:
# instanciando o modelo e sua arquitetura
model = keras.Sequential([
                          keras.layers.Flatten(input_shape=(28, 28)),
                          keras.layers.Dense(128, activation=tf.nn.relu), # 128 neurônios
                          keras.layers.Dense(10, activation=tf.nn.softmax) # 10 neurônios
                          # a última camada é exatemente a quantidade de classe presente no dataset
])

# dados sumarizados do modelo
# mostra quantos pesos tem a rede neural e a estrutura do mesmo e suas camadas
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 128)               100480    
_________________________________________________________________
dense_3 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# compilando o modelo com a função "compile"
model.compile(optimizer='adam', # otimizador para os pesos de treinamento
              loss='sparse_categorical_crossentropy', # métrica de erro -entropia cruzada categórica esparsa
              metrics=['accuracy']) # porcentagem de elementos classificados corretamente sobre o total

In [ ]:
# aplicando o treinamento do modelo e avaliando sua acurácia por épocas
model.fit(train_images, train_labels, 
          epochs=5) # 5 épocas de treinamento - iterações do conjunto de dados

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.6364 - accuracy: 0.7779
Epoch 2/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.3844 - accuracy: 0.8638
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3360 - accuracy: 0.8771
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3092 - accuracy: 0.8870
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2896 - accuracy: 0.8937


In [ ]:
# avaliando acurácia sobre os dados de teste
test_loss, test_acc = model.evaluate(test_images, 
                                     test_labels)
print('Test accuracy: ', test_acc) # acurácia do teste

313/313 [==============================] - 1s 1ms/step - loss: 0.3488 - accuracy: 0.8745
Test accuracy:  0.8744999766349792


In [ ]:
# criando uma variável para avaliar a predição para cada uma das imagens de teste 
predictions = model.predict(test_images) 

In [ ]:
# imprimindo a primeira predição
predictions[0] # um array de 10 elementos com notações científicas
# onde a classificação será dada com a maior valor das predições

array([4.5976827e-09, 8.4506928e-07, 2.9672587e-09, 4.6438800e-10,
       5.9740985e-09, 1.7678109e-03, 1.3262469e-07, 3.6451835e-02,
       3.9933689e-06, 9.6177530e-01], dtype=float32)

In [ ]:
# verificando o índice máximo
np.argmax(predictions[0]) # temos a classe "9"

9

In [ ]:
# avaliando a assertividade do modelo
# para a primeira imagem o modelo acertou
test_labels[0]

9

In [ ]:
# realizando uma avaliação separada - individual de cada uma das imagens
img = test_images[0] # instanciando a imagem de teste [0] na variável "img"
print(img.shape) # imprimindo o shape da imagem - 28 x 28 

(28, 28)


In [ ]:
# o modelo espera um vetor de imagem que seja passado e, aqui só temos uma imagem sozinha
# iremos utlizar o numpy para expandir a dimensão dessa imagem para ter um vetor 
img = (np.expand_dims(img, 0)) # a função "expand_dims" irar expandir a dimensão da imagem colocando dentro de um novo vetor
print(img.shape) # imprimindo o shape do vetor

(1, 28, 28)


In [ ]:
# aplicando essa nova imagem de vetor ao modelo
predictions_single = model.predict(img) # instanciando a predição da única imagem na variável "predictions_single"
print(predictions_single) # imprimindo a variável "predictions_single" com o valor das predições

[[4.5976911e-09 8.4507167e-07 2.9672587e-09 4.6438800e-10 5.9740985e-09
  1.7678109e-03 1.3262495e-07 3.6451872e-02 3.9933689e-06 9.6177530e-01]]


In [ ]:
# efetuando a predição
# retornará o rótulo da primeira imagem
np.argmax(predictions_single[0])

9