<a href="https://colab.research.google.com/github/FGalvao77/others-knowledge-in-python-for-data-science/blob/main/%C3%81lgebra_Linear_fundamentos_e_aplica%C3%A7%C3%B5es_em_Ci%C3%AAncia_de_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Álgebra Linear: fundamentos e aplicações em Ciência de Dados

> ## Tópicos:
1. Vetor
2. Matrizes
3. Sistemas Lineares
4. Determinante
5. Produto interno
6. Norma
7. Combinação Linear
8. Hands On! - Parte I
9. Hands On! - Parte II
10. Próximos passos: Rede Neural
11. Adendos


>> ### 1. Vetor

In [ ]:
import numpy as np

In [ ]:
x = np.array([[1], [7], [-1]])
x

array([[ 1],
       [ 7],
       [-1]])

- Vetor: módulo, direção e sentido (array unidimensional 1-D).

In [ ]:
u = np.array([[1], [2], [3]])
u

array([[1],
       [2],
       [3]])

In [ ]:
type(u)

numpy.ndarray

In [ ]:
u.shape

(3, 1)

In [ ]:
x = np.array([1, 7, -1])
x

array([ 1,  7, -1])

In [ ]:
x.shape = (x.shape[0],1)
x

array([[ 1],
       [ 7],
       [-1]])

In [ ]:
x = np.array([10, 15, 20]).reshape(-1, 1)
x

array([[10],
       [15],
       [20]])

Igualdade

In [ ]:
u = np.array([1, 4, 100])
v = np.array([1, np.log2(16), np.power(10, 2)])

In [ ]:
u == v

array([ True,  True,  True])

Soma e multiplicação por escalar

In [ ]:
u = np.array([11, 12, 13])
v = np.array([9, 3, 2])
u + v

array([20, 15, 15])

In [ ]:
10 * u


array([110, 120, 130])

Produto escalar (ou produto interno)


In [ ]:
sum(u * v)

161

In [ ]:
np.inner(u,v)

161

Dois vetores são ortogonais ou perpendiculares se o produto interno entre eles for nulo.


In [ ]:
u = np.array([3,-4])

In [ ]:
np.sqrt(np.inner(u, u))

5.0

Generalizando para o Rn podemos definir todas as operações anteriores.

>> ### 2. Matriz
  - representação tabular de dados;
  - notação: Am × n.

In [ ]:
import numpy as np

In [ ]:
matrix = np.array([[-11, 2], [7, 15]])

In [ ]:
matrix

array([[-11,   2],
       [  7,  15]])

In [ ]:
type(matrix)

numpy.ndarray

In [ ]:
matrix.shape

(2, 2)

In [ ]:
matrix.ndim #número de dimensões

2

>>> #### 2.1 Matrizes importantes



1. Matriz Quadrada: matriz em que o número de linhas é igual ao número de colunas (m = n).

In [ ]:
A = np.array([[-1, 2], [4, 5]])

In [ ]:
A

array([[-1,  2],
       [ 4,  5]])

1. Matriz Nula: matriz em que todos os elementos são nulos, ou seja, aij = 0 para todo i e j.


In [ ]:
B = np.array([[0, 0, 0], [0, 0, 0]])
B

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
B = np.zeros(shape = (2, 3))
B

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
K = np.zeros(shape = (10, 10))
K

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

1. Matriz-Coluna: matriz que possui uma única coluna (Am × 1
).

In [ ]:
C = np.array([[-1], [2], [10], [5]])
C

array([[-1],
       [ 2],
       [10],
       [ 5]])

1. Matriz-Linha: matriz com uma única linha (A1 × n
)


In [ ]:
D = np.array([-1, 2, 10, 5])
D

array([-1,  2, 10,  5])

1. Matriz diagonal: matriz quadrada em que qualquer elemento fora da diagonal principal é nulo, isto é,
aij = 0 para i ≠ j.


In [ ]:
E = np.diag(np.arange(5,16,5))
E

array([[ 5,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 15]])

1. Matriz identidade: matriz em que aij = 1 , ∀i = j e aij = 0, ∀i ≠ j. Assim, a matriz identidade, ou matriz
unitária, de ordem n, denotada por In
 ou, simplesmente, por I, é a matriz quadrada com 1 na diagonal
principal e 0 em todas as demais entradas. A matriz identidade I é análoga ao escalar 1, pois, dada
qualquer matriz Am × n
, temos que AI = IA = A. Para uma matriz Bn × 1
, verifica-se IB = B

In [ ]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

1. Matriz simétrica: matriz quadrada em que aij = aji
 para quaisquer i, j e A
T = A.


In [ ]:
F = np.array([[4, 3, -1], [3, 2, 0], [-1, 0, 5]])
F

array([[ 4,  3, -1],
       [ 3,  2,  0],
       [-1,  0,  5]])

In [ ]:
F.T == F

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

1. Matriz Idempotente: matriz quadrada em que A ⋅ A = A .

In [ ]:
L = np.array([[5, -5], [4, -4]])
L

array([[ 5, -5],
       [ 4, -4]])

In [ ]:
np.dot(L, L)

array([[ 5, -5],
       [ 4, -4]])

>>> #### 2.2 Operações matriciais
2.2.1 Adição e multiplicação por escalar
As matrizes precisam ter a mesma ordem.

In [ ]:
A = np.array([[1, 3], [2, 7]])
B = np.array([[2, 5], [5, 3]])
soma = A+B
soma

array([[ 3,  8],
       [ 7, 10]])

Produto por escalar

In [ ]:
10 * A

array([[10, 30],
       [20, 70]])

2.2.2 Multiplicação de matrizes
- Multiplicação entre uma matriz linha e uma matriz coluna

In [ ]:
u = np.array([1, 5, 10])
v = np.array([[2], [3], [2]])


In [ ]:
u

array([ 1,  5, 10])

In [ ]:
v

array([[2],
       [3],
       [2]])

In [ ]:
np.dot(u,v)


array([37])

- Caso geral de multiplicação de matrizes
Am × p
⋅ Bp × n = Cm × n
O elemento cij
 será obtido por meio da multiplicação dos elementos da i-ésima linha da primeira matriz pelos
correspondentes elementos da j-ésima coluna da segunda matriz, com a posterior soma destes produtos.


In [ ]:
A = np.array([[2, 1], [4, 2], [5, 3]])
B = np.array([[1, -1], [0, 4]])
C = np.dot(A,B)
C

array([[2, 2],
       [4, 4],
       [5, 7]])

>>> #### 2.3 Matriz transposta
A transposta de uma matriz A, denotada por A
T
 ou A
′
, é a matriz obtida escrevendo as colunas de A, na
mesma ordem, como linhas.


In [ ]:
A = np.array([[1, 7], [8, 3], [1, 2]])
A


array([[1, 7],
       [8, 3],
       [1, 2]])

In [ ]:
A.T


array([[1, 8, 1],
       [7, 3, 2]])

In [ ]:
A.transpose()


array([[1, 8, 1],
       [7, 3, 2]])

>>> #### 2.4 Traço de uma matriz
O traço de uma matriz quadrada A, denotado por tr(A), é a soma dos elementos da diagonal principal, a
saber, tr(A) = a11 + a22 + a33 + . . . + ann

In [ ]:
A = np.array([[2, 7, 1], [8, 3, 2], [1, 2, 10]])
A.trace()


15

>>> #### 2.5 Matriz Inversa
Uma matriz quadrada A é dita invertível, ou não singular, se existir uma matriz B tal que AB = BA = I onde I é
a matriz identidade. Uma tal matriz B é única.


In [ ]:
Z = np.array([[3,4],[1,0]])
Z_inv = np.linalg.inv(Z)


In [ ]:
Z_inv

array([[ 0.  ,  1.  ],
       [ 0.25, -0.75]])

In [ ]:
Z.dot(Z_inv)


array([[1., 0.],
       [0., 1.]])

> # Dinâmica 1

>> ## 3. Sistemas Lineares
- Um sistema linear pode ter uma única solução, múltiplas soluções ou nenhuma solução.


In [ ]:
A = np.array ([[3, -7], [5, 2]])
B = np.array([[1], [4]])

In [ ]:
X = (np.linalg.solve(A, B))


In [ ]:
X #solução do sistema


array([[0.73170732],
       [0.17073171]])

> # 4. Determinante
- Podemos pensar no determinante como um número associado a uma matriz quadrada Am × n
. Denotamos
det A.

Basta utilizar a função np.linalg.det()


In [ ]:
V = np.array([[1, 2, 3, 4], [4, 3, 1, 1], [0, 2, 4, 6], [5, 7, 9, 1]])

In [ ]:
round (np.linalg.det(V))


-20

> # 5. Produto interno
Produto interno canônico:

In [ ]:
i = np.array([1, 0, 0])
j = np.array([0, 1, 0])
k = np.array([0, 0, 1])

In [ ]:
np.inner(i,j)


0

In [ ]:
np.inner(j,k)

0

Se dois vetores x, y, em um dado espaço vetorial possuem produto interno nulo, então esses vetores são
ortogonais.


> # 6. Norma
Seja x ∈ R
n
, o número | x | é denominado norma euclidiana ou distância.

> # 7. Combinação Linear
Sejam v
1
, v
2
, …v
n
 vetores de um espaço vetorial V e os escalares reais a1
, a2
, …an
. Qualquer vetor v ∈ V, tal
que v = a1v1 + a2v2 + a3v3 + …anvn
 é uma combinação linear dos vetores v1
, v2
, …, vn
.


In [ ]:
u = np.array([1, 0])
v = np.array([0, 1])
w = np.array([3, 2])


In [ ]:
3 * u + 2 * v

array([3, 2])

# Dinâmica 2

8. Hands On! - Parte 1
 1. Encontre WI sendo W =
1 3 0 20
2 −1 10 13
3 4 10 0
4 9 −1 0
 e I =
2 0
−4 11
5 −2 [ ] [ 6 0 ]

 1. Construa uma matriz 5 × 5 e encontre traço, diagonal principal e secundária.

 1. Crie uma matriz 2 × 2 somente com elementos pares e calcule seu determinante.

 1. Represente os sistemas abaixo na forma matricial e encontre as respectivas soluções.
a)
2x + y = 5
x − 3y = 0
b)
2a + b + c = − 1
a + c = 0
−3a + 5b − c = 2
{
{

 1. Determine a inversa das matrizes:
a) H =
1 0
3 0
b) I =
1 0 0
1 3 1
1 2 0
[ ]
[ ]


# 9. Hands On! - Parte 2

1. Com base nos dados gerados a seguir obtenha a matriz de coeficientes da regressão linear e em
seguida utilize a biblioteca Statsmodels para verificar os resultados obtidos.


In [ ]:
from sklearn.datasets import make_regression
X, y = make_regression(n_samples = 1000, n_features = 10, random_state = 99)

1. Use a biblioteca sklearn para ajustar um modelo de regressão linear com base nas matrizes anteriores,
calcule ainda outras métricas de avaliação da regressão. Use a função train_test_split() para separar os
dados em treino e teste com random_state igual a 55.

1. Faça:
 a. Importe o banco de dados anexo nesta aula (kc_house_data.csv);

 b. Mostre as 5 primeiras linhas;

 c. Mostre as colunas e o índice do dataset;

 d. Mostre o shape do dataset;

 e. Mostre informações do objeto criado com a função info();

 f. Mostre o dtype de cada coluna;

 g. Remova as seguintes colunas: 'id', 'date', 'zipcode', 'lat', 'long';

 h. Verifique se há missing data no dataset;

 i. Mostre estatísticas descritivas do dataset com a função describe();

 j. Calcule a matriz de correlação;

 l. Calcule a matriz de covariância;

 m. Faça um mapa de calor com base na matriz de correlação, use o módulo Seaborn;

 n. Faça um gráfico das relações entre as variáveis do dataset com a função pairplot do módulo Seaborn;

 o. Defina a variável target (coluna 'price') e armazene em uma variável;

 p. Defina as variáveis preditoras, que serão utilizadas para explicar o preço, e armazene em uma variável;

 q. Use a função train_test_split do sklearn para separar o dataset em dados de treino e teste, defina o
test_size = 0.3 e random_state = 33;

 r. Crie um modelo de regressão linear e ajuste aos dados de treino, use: from sklearn.linear_model import
LinearRegression;

 s. Calcule o coeficiente de determinação do modelo com a função score(), passando os dados de teste;